# Base node image
FROM node:18-bullseye-slim

# Set working directory
WORKDIR /app

# Set environment to production
ENV NODE_ENV production

# Install system dependencies
RUN apt-get update && apt-get install -y openssl

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy project files
COPY . .

# Build the application
RUN npm run build

# Expose port
EXPOSE $PORT

# Start command
CMD ["npm", "start"]